### ISSUE TITLE
File exists error

### ISSUE THREAD

**Issue by oushujun** [zhangrengang/TEsorter#22]
Hi Ren-gang,

I want to execute multiple TEsorter runs in the same folder and encounter the file exists error. Is it possible to tolerate this, for example, by creating `./tmp` directories with a random number in the name?

>2021-01-03 07:54:26,915 -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH
2021-01-03 07:54:26,920 -INFO- VARS: {'sequence': 'B73.PLATINUM.pseudomolecules-v1.fasta.mod.EDTA.intact.gff3.LTR.fa', 'hmm_database': 'rexdb', 'seq_type': 'nucl', 'prefix': 'B73.PLATINUM.pseudomolecules-v1.fasta.mod.EDTA.intact.gff3.LTR.fa.rexdb', 'force_write_hmmscan': False, 'processors': 36, 'tmp_dir': './tmp', 'min_coverage': 20, 'max_evalue': 0.001, 'disable_pass2': False, 'pass2_rule': '80-80-80', 'no_library': False, 'no_reverse': False, 'no_cleanup': False, 'p2_identity': 80.0, 'p2_coverage': 80.0, 'p2_length': 80.0}
2021-01-03 07:54:26,921 -INFO- checking dependencies:
2021-01-03 07:54:26,931 -INFO- hmmer    3.3.1   OK
2021-01-03 07:54:29,064 -INFO- blastn   2.10.0+ OK
Traceback (most recent call last):
  File "/home/oushujun/las/bin/miniconda2/envs/EDTA5/bin/TEsorter", line 10, in <module>
    sys.exit(main())
  File "/home/oushujun/las/bin/miniconda2/envs/EDTA5/lib/python3.6/site-packages/TEsorter/app.py", line 1014, in main
    pipeline(Args())
  File "/home/oushujun/las/bin/miniconda2/envs/EDTA5/lib/python3.6/site-packages/TEsorter/app.py", line 149, in pipeline
    os.makedirs(args.tmp_dir)
  File "/home/oushujun/las/bin/miniconda2/envs/EDTA5/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: './tmp'

Thanks!
Shujun

**Comment by zhangrengang** [comment]
Hi @oushujun ，I have added uuid and the tmpdir will be, for example, './tmp-9f70c9d4-62a2-11eb-8aa7-a0369fc22fb8'.
