### ISSUE TITLE
RuntimeError: Communication pipe read error

### ISSUE THREAD

**Issue by zouxq97** [zhangrengang/TEsorter#23]
Hi Ren-gang,
    I recently install TEsorter and encounter something wrong with the running by executing command  "nohup python3.9 /home/bin/TEsorter xx_whole_genome_te.fa &".there are part of report just like 
"2021-04-14 11:29:12,545 -INFO- Running on Python 3.9.1 linux
Traceback (most recent call last):
  File "/home/bin/TEsorter", line 33, in <module>
    sys.exit(load_entry_point('TEsorter==1.2.5.2', 'console_scripts', 'TEsorter')())
  File "/home/lib/python3.9/site-packages/TEsorter-1.2.5.2-py3.9.egg/TEsorter/app.py", line 976, in main
    pipeline(Args())
  File "/home/lib/python3.9/site-packages/TEsorter-1.2.5.2-py3.9.egg/TEsorter/app.py", line 155, in pipeline
    gff, geneSeq = LTRlibAnn(
  File "/home/lib/python3.9/site-packages/TEsorter-1.2.5.2-py3.9.egg/TEsorter/app.py", line 884, in LTR
libAnn
    hmmscan_pp(aaSeq, hmmdb=DB[hmmdb], hmmout=domtbl, tmpdir=tmpdir, processors=processors)
  File "/home/lib/python3.9/site-packages/TEsorter-1.2.5.2-py3.9.egg/TEsorter/app.py", line 850, in hmm
scan_pp
    jobs = pp_run(cmds, processors=processors)
  File "/home/lib/python3.9/site-packages/TEsorter-1.2.5.2-py3.9.egg/TEsorter/modules/RunCmdsMP.py", li
ne 260, in pp_run
    job_server = pp.Server(processors, ppservers=ppservers)
  File "/home/lib/python3.9/site-packages/pp-1.6.4.4-py3.9.egg/pp.py", line 372, in __init__
    self.set_ncpus(ncpus)
  File "/home/lib/python3.9/site-packages/pp-1.6.4.4-py3.9.egg/pp.py", line 540, in set_ncpus
    self.__workers.extend([_Worker(self.__restart_on_free, 
  File "/home/lib/python3.9/site-packages/pp-1.6.4.4-py3.9.egg/pp.py", line 540, in <listcomp>
    self.__workers.extend([_Worker(self.__restart_on_free, 
  File "/home/lib/python3.9/site-packages/pp-1.6.4.4-py3.9.egg/pp.py", line 161, in __init__
    self.start()
  File "/home/lib/python3.9/site-packages/pp-1.6.4.4-py3.9.egg/pp.py", line 175, in start
    self.pid = int(self.t.receive())
  File "/home/lib/python3.9/site-packages/pp-1.6.4.4-py3.9.egg/pptransport.py", line 179, in receive
    raise RuntimeError("Communication pipe read error")
RuntimeError: Communication pipe read error"
I really don't know how to solve it. I will appreciate it if you can feedback any suggestions.

**Comment by zhangrengang** [comment]
I am sorry I missed your email. The issue maybe because of incompatibility of `pp`. I have replaced `pp` instead of `multiprocessing`. Please try the updated version.
