### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 123123456abc** [zhangrengang/TEsorter#35]
Dear author, I encountered an error when running the software.Encountered a problems，could you please help me check the reason? I have attached the command line and log below, thank you very much

Traceback (most recent call last):
  File "/home/appl/anaconda3/envs/TEsorter/bin/TEsorter", line 10, in <module>
    sys.exit(main())
  File "/home/appl/anaconda3/envs/TEsorter/lib/python3.10/site-packages/TEsorter/app.py", line 1014, in main
    pipeline(Args())
  File "/home/appl/anaconda3/envs/TEsorter/lib/python3.10/site-packages/TEsorter/app.py", line 174, in pipeline
    for rc in Classifier(gff, db=args.hmm_database, fout=fc):
  File "/home/appl/anaconda3/envs/TEsorter/lib/python3.10/site-packages/TEsorter/app.py", line 414, in classify
    order, superfamily, max_clade, coding = self.identify_rexdb(genes, names)
  File "/home/appl/anaconda3/envs/TEsorter/lib/python3.10/site-packages/TEsorter/app.py", line 430, in identify_rexdb
    order, superfamily = self._parse_rexdb(max_clade)
  File "/home/appl/anaconda3/envs/TEsorter/lib/python3.10/site-packages/TEsorter/app.py", line 470, in _parse_rexdb
    logger.warning( 'unknown clade: {}'.format(max_clade) )
NameError: name 'max_clade' is not defined

**Comment by zhangrengang** [comment]
Hi @123123456abc, can you send me your input fasta file via email (zhangrengang@ori-gene.cn)? This error should not be reach.
