### ISSUE TITLE
Problem with concatenate_domains.py

### ISSUE THREAD

**Issue by yliasolom** [zhangrengang/TEsorter#43]
Please could you help:

when I run this command: concatenate_domains.py

I got this:
Traceback (most recent call last):
  File "/home/iuliiasolomennikova/miniconda3/envs/LTR_rert/bin/concatenate_domains.py", line 33, in <module>
    sys.exit(load_entry_point('TEsorter==1.4.5', 'console_scripts', 'concatenate_domains.py')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iuliiasolomennikova/miniconda3/envs/LTR_rert/bin/concatenate_domains.py", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^

**Comment by zhangrengang** [comment]
Hi @yliasolom, you may need to run with input, like below:
```
concatenate_domains.py rice6.9.5.liban.rexdb.cls.pep RT RH INT > rice6.9.5.liban.rexdb.cls.pep_RT_RH_INT.aln
```
