### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by EdgarLW** [zhangrengang/TEsorter#55]
Hello,

I've been recently using TEsorter on a couple of genomes and have encountered a peculiar error:
```
...
024-07-02 20:08:38,699 -INFO- translating ./tmp-ef4e9b00-389d-11ef-9960-248a075bf030/chunk.64.fasta in six frames
2024-07-02 20:09:05,508 -INFO- use existed non-empty plant.genome.TElib.fa.rexdb-plant.domtbl and skip hmmscan
2024-07-02 20:09:05,509 -INFO- generating gene anntations
Traceback (most recent call last):
  File "/usr/local/bin/TEsorter", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/TEsorter/app.py", line 1248, in main
    pipeline(Args())
  File "/usr/local/lib/python3.12/site-packages/TEsorter/app.py", line 244, in pipeline
    gff, geneSeq = LTRlibAnn(
                   ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/TEsorter/app.py", line 1151, in LTRlibAnn
    gff, geneSeq = hmm2best(chunk_files, [domtbl], db=db_name, nucl_len=d_nucl_len, genome=genome,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/TEsorter/app.py", line 928, in hmm2best
    d_besthit = _hmm2best(inHmmouts, db=db, seqtype=seqtype, genome=genome)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/TEsorter/app.py", line 881, in _hmm2best
    rc.score = round(rc.domscore / rc.tlen, 2)
                     ~~~~~~~~~~~~^~~~~~~~~
```

Is there any easy fix to this? I've ran the default command with flags for `-db rexdb-plant` and `-p 32`

**Comment by zhangrengang** [comment]
The  *domtbl file maybe broken. Please set `-fw` and retry.

**Comment by EdgarLW** [comment]
Just finished the second run, everything went smoothly. Thank you so much for the quick response and the help! ;)
