### ISSUE TITLE
RepeatMasker.py

### ISSUE THREAD

**Issue by Ssmile333** [zhangrengang/TEsorter#8]
Traceback (most recent call last):
  File "/data/storage02/chenss/soft/TEsorter/bin/RepeatMasker.py", line 143, in <module>
    main()
  File "/data/storage02/chenss/soft/TEsorter/bin/RepeatMasker.py", line 130, in main
    subcmd = sys.argv[1]
IndexError: list index out of range

**Comment by zhangrengang** [comment]
`RepeatMasker.py out2seqs` needs three position arguments, such as:
```
python [path_to_TEsorter]/bin/RepeatMasker.py out2seqs genome.fa.out genome.fa > whole_genome_te.fa
```
